version: '3.8'
services:
  app-banner:
    image: app-banner:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - stack.env
    restart: unless-stopped