version: '3.8'

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    working_dir: /app