version: '3.8'
services:
  app-banner:
    image: app-banner:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped